# Generated by Django 3.1.5 on 2021-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.TextField()),
                ('foldername', models.TextField()),
                ('filedic', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='fd',
        ),
    ]
