# Generated by Django 3.1.4 on 2021-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0003_auto_20210123_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='ff',
            field=models.ImageField(upload_to='fm'),
        ),
    ]
