# Generated by Django 3.1.4 on 2021-01-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0005_auto_20210125_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='ff',
            field=models.FileField(upload_to=''),
        ),
    ]
