# Generated by Django 3.1.4 on 2021-03-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trav', '0006_auto_20210125_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='fdic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.TextField()),
                ('filedic', models.TextField()),
            ],
        ),
    ]
